### ISSUE TITLE
NativeLibraryLoader throws on full CLR

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#197]
Using TD.NET with latest changes (#192)

```
Test 'Microsoft.Data.Entity.Sqlite.Design.FunctionalTests.ReverseEngineering.SqliteAttributesInsteadOfFluentApiE2ETest.Principal_missing_primary_key' failed:
	System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
---- System.ArgumentNullException : Value cannot be null.
Parameter name: element
	at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
	at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
	at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
	at Microsoft.Data.Sqlite.Utilities.NativeLibraryLoader.IsDNX()
```

**Comment by natemcmaster** [comment]
Moving to https://github.com/aspnet/PlatformAbstractions/issues/2
