### ISSUE TITLE
Sqlite's DbDataReader doesn't support DataTable.Load.

### ISSUE THREAD

**Issue by tiandian** [aspnet/Microsoft.Data.Sqlite#395]
My below code doesn't work because sqlite's DbDataReader.GetSchemaTable doesn't implement.

```
DataTable dt = new DataTable();
using (DbDataReader ddr = this.ExecuteReader(strSql))
 { dt.Load(ddr); }
```
Below is the error:
```
System.NotSupportedException occurred
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Data.Common.DbDataReader.GetSchemaTable()
   at System.Data.ProviderBase.SchemaMapping..ctor(DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, Boolean keyInfo, SchemaType schemaType, String sourceTableName, Boolean gettingData, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMappingInternal(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMapping(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   at System.Data.DataTable.Load(IDataReader reader)
```

thanks.

**Comment by bricelam** [comment]
*Copying my comment from #253:*

This specific error is likely only the tip of the iceberg. I believe we'd need to implement `DbCommandBuilder` too to support generating the appropriate queries.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address.  This does not mean that we would not consider a community contribution to address this issue.

**Comment by bricelam** [comment]
I eat my words. This works after #253.
