### ISSUE TITLE
NullRef related to update_hook

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#441]
We got an interesting `NullReferenceException` on our CI that we should investigate and try to reproduce:

    System.NullReferenceException : Object reference not set to an instance of an object.
       at SQLitePCL.SQLite3Provider_e_sqlite3.update_hook_bridge_impl(IntPtr p, Int32 typ, IntPtr db, IntPtr tbl, Int64 rowid)
       at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_step(IntPtr stmt)
       at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_step(IntPtr stm)
       at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

My initial thought is that we may need to unregister the `sqlite3_update_hook` callback when the connection is finalized/disposed.

**Comment by bricelam** [comment]
cc @ericsink in case it looks familiar

**Comment by ericsink** [comment]
Interesting.

No, that does not look familiar.  But now I'm curious about it.

**Comment by smitpatel** [comment]
Slightly different stack trace
```
Assert.Throws() Failure
Expected: typeof(Microsoft.Data.Sqlite.SqliteException)
Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
   at SQLitePCL.SQLite3Provider_e_sqlite3.agg_function_hook_bridge_final_impl(IntPtr context)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_finalize(IntPtr stmt)
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_finalize(IntPtr stm)
   at SQLitePCL.raw.sqlite3_finalize(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.DisposePreparedStatements() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs:line 561
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs:line 203
   at System.ComponentModel.Component.Dispose()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteScalar(SqliteConnection connection, String commandText) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\src\Microsoft.Data.Sqlite.Core\Extensions\SqliteConnectionExtensions.cs:line 31
   at Microsoft.Data.Sqlite.SqliteConnectionTest.<>c__DisplayClass46_0.<CreateAggregate_works_when_exception_during_step>b__1() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\Microsoft.Data.Sqlite\test\Microsoft.Data.Sqlite.Tests\SqliteConnectionTest.cs:line 672
```

**Comment by ryanbrandenburg** [comment]
We got a lot of examples of this [here](http://aspnetci/viewLog.html?buildId=357928&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe).

**Comment by ryanbrandenburg** [comment]
More examples [here](http://aspnetci/viewLog.html?buildId=360662&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by bricelam** [comment]
Reverted feature #357 until we can investigate and fix this issue.

**Comment by bricelam** [comment]
Closing as a duplicate of #357
