### ISSUE TITLE
[2.0.1] Sqlite transaction tests fail on Linux

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#476]
I believe this was a result of #475 

```
Microsoft.Data.Sqlite.SqliteException : SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel) in /datadrive/5ab5bfc195c9b71/modules/EntityFrameworkCore/src/EFCore.Relational/Storage/RelationalConnection.cs:line 185
   at Microsoft.EntityFrameworkCore.TransactionTestBase`2.UseTransaction_throws_if_another_transaction_started(Boolean autoTransaction) in /datadrive/5ab5bfc195c9b71/modules/EntityFrameworkCore/src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs:line 609
```

http://aspnetci/viewLog.html?buildId=385651&tab=buildResultsDiv&buildTypeId=Patches_20x_Public_TestUbuntu

cc @ajcvickers @bricelam

**Comment by ryanbrandenburg** [comment]
It seems like this affects dev now: http://aspnetci/viewLog.html?buildId=388046&tab=buildResultsDiv&buildTypeId=Lite_EntityFrameworkTest

**Comment by bricelam** [comment]
Ah, looks like there were new tests added that weren't covered by merging. Will fix.
