### ISSUE TITLE
Guidelines for loadable extensions on Windows

### ISSUE THREAD

**Issue by turbo** [aspnet/Microsoft.Data.Sqlite#479]
Due to the lack(?) of a helper method to load loadext from files, I'm issuing this query:

```csharp
if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                Connection.Query($"SELECT load_extension('{binDir}lib/linux/amd64/closure');");
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                Connection.Query($"SELECT load_extension('{binDir}lib/macos/closure');");
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                var lib = $"{binDir}lib\\windows\\closure";
                Console.WriteLine(lib);
                Connection.Query($"SELECT load_extension('{lib}');");
            }
            else
                throw new NotImplementedException("Eugh, no binary for you yet.");
```

My dotnet core 2.1.4, C# 7.2 project using M.D.Sqlite 2.0.0 targets `ubuntu-x64`, `osx-x64` and `windows-x64`. On the unix platforms, this works great. However on Windows, I can't get the extension to load for the life of me:

```text
C:\Users\turbo\prj\bin\debug\lib\windows\closure

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'The specified module could not be found.
'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1053
   at Dapper.SqlMapper.<QueryImpl>d__136`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
   at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 650
```

The path exists and is correct for the DLL. I've compiled it using MSYS2 as follows:

```sh
gcc -fPIC -lm -shared closure.c -o closure.dll
```

using GCC 6.4.0.

What's the recommended method to compile loadext on Windows? Is there a better way to load extensions using this package rather than issuing the select?

**Comment by turbo** [comment]
I've now got it to compile using MSVC: `cl closure.c -DSQLITE_API=__declspec(dllexport) -link -dll /MACHINE:X86 -out:closure.dll`.

Now the Windows build of SQLite can load it just fine:

```text
sqlite3
sqlite> .load closure
sqlite> .exit
```

But I get a different exception from this package:

```text
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: '%1 is not a valid Win32 application.
'.
```

**Comment by turbo** [comment]
I have now compiled it using the x64 toolchain (`cl closure.c -DSQLITE_API=__declspec(dllexport) -link -dll /MACHINE:X64 -out:closure.dll`) and ... onto the next exception. This time SQLite claims `load_extension` doesn't exist ...

```text
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'The specified procedure could not be found.
```

**Comment by turbo** [comment]
Yay, I solved it. It turns out that the sqlite version shipped by PCLraw can't be bothered finding the entry point, so 

```csharp
Connection.Query($"SELECT load_extension('{lib}', 'sqlite3_closure_init');");
```

will work.
