### ISSUE TITLE
SQLite Error 1: no such table

### ISSUE THREAD

**Issue by StefanoD** [aspnet/Microsoft.Data.Sqlite#505]
Hi,

I get sometimes errors like these:

```
2018-04-17 11:49:24.0195|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLD48P531NNM", Request id "0HLD48P531NNM:00000004": An unhandled exception was thrown by the application. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'no such table: AuditTrail'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at QLCConnectServer.Controllers.AuthentificationLoggerController.LogLoggedOut(QlcAuditLogRequest qlcAuditLogRequest) in D:\development\ESLR22-SO-0010_Connect\sources\QLCConnectServer\QLCConnectServer\Controllers\AuthentificationLoggerController.cs:line 69
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```
The exception seems to be thrown, when the method goes out of scope:
```C#
public IActionResult LogLoggedOut([FromBody]QlcAuditLogRequest qlcAuditLogRequest)
{
	if (!ModelState.IsValid) return BadRequest(ModelState);

	AuditTrail auditTrail = new AuditTrail(
		Severity.TRACE,
		DateTime.UtcNow,
		qlcAuditLogRequest.User,
		"Logged out");

	_dbContext.AuditTrail.Add(auditTrail);
	_dbContext.SaveChanges();

	return Ok(); // Thrown here!
}
```
Is it a problem, that I close the connection in the destructor of my Context class?!
```C#
public class QlcContext : DbContext
{
	public DbSet<AuditTrail> AuditTrail { get; set; }

	private SqliteConnection connection;

	public QlcContext(DbContextOptions<QlcContext> options) : base(options)
	{
	}

	public QlcContext()
	{
	}

	public override void Dispose()
	{
		base.Dispose();
		connection?.Close(); // Close Connection on Destructor!
	}

	protected override void OnConfiguring(DbContextOptionsBuilder contextOptionsBuilder)
	{
		string connectionString = DataController.Instance.DbConnectionString;

		connection = new SqliteConnection(connectionString);
		connection.Open();

		string password = "myPass";

		var command = connection.CreateCommand();
		command.CommandText = "SELECT quote($password);";
		command.Parameters.AddWithValue("$password", password);
		var quotedPassword = (string)command.ExecuteScalar();

		command.CommandText = "PRAGMA key = " + quotedPassword;
		command.Parameters.Clear();
		command.ExecuteNonQuery();

		contextOptionsBuilder.UseSqlite(connection);
	}
}
```

I use following packages:

```XML
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.2" />
<PackageReference Include="Microsoft.Data.SQLite" Version="2.0.1" />
<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="2.0.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
<PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.10" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="1.1.10" ExcludeAssets="All" />
```

**Comment by StefanoD** [comment]
I close this, until I investigated it better.

**Comment by StefanoD** [comment]
I guess, my collegue, who reported me this error, deleted the database while my server was still running.

**Comment by bricelam** [comment]
😄 Oh man! That'll do it...
