### ISSUE TITLE
Multi-threaded environment occasionally throws "bad parameter or other API misuse" Error (21)

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Microsoft.Data.Sqlite#508]
Here I'm NOT talking about concurrent using of a single connection from many threads (which is bad), but creating and using several connections in concurrent threads. That means 1-to-1 relation between thread and connection. This should be totally legit.

If we'll be using CreateFunction in one of concurrent threads then in the others we'll get Microsoft.Data.Sqlite.SqliteException on calling `ExecuteNonQuery` (or similar methods):
SQLite Error 21: 'bad parameter or other API misuse For more information on this error code see http://sqlite.org/rescode.html'.
stack:
```
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__62.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
```

Microsoft.Data.Sqlite#2.1.0-preview2.

Code that reproduces the bug we can find below.

The bug is pretty important as I can't see how to workaround it. It'd make us to add synchronization code for every command execution code. But what to do with reading via DataReader? Should we synchronize the whole reading from datareader or just its creation (ExecuteReader)? Anyway it'd pollute user code.

Demo:
```csharp
using System;
using System.Threading;
using System.IO;
using Microsoft.Data.Sqlite;

namespace sqlite
{
    class Program
    {
    	static void execute(SqliteConnection con, string cmdText) 
    	{
			var cmd = con.CreateCommand();
			cmd.CommandText = cmdText;
			cmd.ExecuteNonQuery();
    	}

    	static void registerFunctions(SqliteConnection connection)
    	{
			connection.CreateFunction("UPPER", (string str) => str?.ToUpper());
    	}

        static void Main(string[] args)
        {
        	{
        	File.Delete("test.db");
       		var con = new SqliteConnection();
     		con.ConnectionString = "Data Source=test.db";
			con.Open();
			execute(con, "create table t1(int i)");
			execute(con, "insert into t1 values (1)");
			con.Close();
			}
			for(int i = 0; i < 100; i++) {
				Console.Write(i);

				var startEvent = new ManualResetEvent(false);
				Thread t1 = new Thread(() => {
					startEvent.WaitOne();
        			var con = new SqliteConnection();
        			con.ConnectionString = "Data Source=test.db";
					con.Open();
					registerFunctions(con);
					execute(con, "insert into t1 values (" + i + " )");
					con.Close();
				});
				Thread t2 = new Thread(() => {
					startEvent.WaitOne();
	        		var con = new SqliteConnection();
        			con.ConnectionString = "Data Source=test.db";
					con.Open();
					execute(con, "insert into t1 values (" + i + " )");
					registerFunctions(con);
					con.Close();
				});
				t1.Start();
				t2.Start();
				startEvent.Set();

				t1.Join();
				t2.Join();

				Console.WriteLine("...OK");
			}

            Console.WriteLine("OK.");
        }
    }
}
```

**Comment by AlexanderTaeschner** [comment]
I'm not sure what is really happening (the SQLITE_MISUSE error is returned by `sqlite3_prepare_v2` in `PrepareAndEnumerateStatements`). Using your code, the following workaround works for me: use "Data Source=test.db;Cache=Shared" as connection string.

**Comment by v1rusw0rm** [comment]
I'm using EF Core 2.1.0-preview2 with Microsoft.Data.Sqlite 2.1.0-preview2 in ASP.NET Core WebAPI controller. The controller action just returns all rows like `return _dbContext.Entities.ToList();`. Same bug is consistently appearing during load testing with ~100s simultaneous requests. Stacktrace:
```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 21: 'bad parameter or other API misuse For more information on this error code see http://sqlite.org/rescode.html'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
The workaround with shared cache works for me too, but is it safe in terms of bugs and stability?

**Comment by AlexanderTaeschner** [comment]
@v1rusw0rm: Do you also use CreateFunction? Unfortunately I cannot comment on the safety of the workaround (from the SQLite FAQ: Threads are evil. Avoid them.).
@ericsink: Is it possible for you to debug the example from above down to the C code of SQLite, to see concrete reason for the SQLITE_MISUSE error (no extended error code is provided)?

**Comment by bricelam** [comment]
Doh, I see what's going on... When we retry on busy, we pass `null` into `sqlite3_prepare_v2()`:
``` csharp
while (IsBusy(rc = raw.sqlite3_prepare_v2(_connection.Handle, tail, out stmt, out tail)))
```
We need to keep the `tail` going in the same between retires, but it's changed by `out tail`.

**Comment by ericsink** [comment]
Well, I *was* going to acknowledge the @ above and say that I would dig into this, but it appears that a bit of procrastination has paid off nicely.
